### ISSUE TITLE
Crash in prefer-filter

### ISSUE THREAD

**Issue by Lalem001** [wix/eslint-plugin-lodash#108]
**test.js**

```javascript
'use strict';

const forEach = require('lodash/forEach');
const noop = require('lodash/noop');

const callbacks = [noop, noop];

// Crash occurs on next line
forEach(callbacks, noop);
```

**.eslint.json**

```json
{
	"plugins": ["lodash"],
	"extends": ["plugin:lodash/recommended"]
}
```

**Exception**

```console
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at onlyHasSimplifiableIf ([redacted]/node_modules/eslint-plugin-lodash/lib/rules/prefer-filter.js:53:68)
    at [redacted]/node_modules/eslint-plugin-lodash/lib/rules/prefer-filter.js:60:64
    at EventEmitter.<anonymous> ([redacted]/node_modules/eslint-plugin-lodash/lib/util/lodashUtil.js:236:17)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode ([redacted]/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode ([redacted]/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode ([redacted]/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter ([redacted]/node_modules/eslint/lib/eslint.js:898:36)
    at Controller.__execute ([redacted]/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse ([redacted]/node_modules/estraverse/estraverse.js:501:28)
```

**Comment by ganimomer** [comment]
Thanks for reporting!
Fixed in version `2.1.2`.
