### ISSUE TITLE
prefer-over-quantifier.js causes exception

### ISSUE THREAD

**Issue by njlg** [wix/eslint-plugin-lodash#111]
When I try to lint my project with `eslint-plugin-lodash@2.1.3` I get the following exception.

```
/Users/nlevingreenhaw/source/app/node_modules/eslint-plugin-lodash/lib/rules/prefer-over-quantifier.js:74
            if (callType === 'chained' && iteratee.type === 'Identifier' && isObjectOfMethodCall(node) && isCallToConditionMethod(getMethodName(node.parent.parent), version) && onlyPassesIdentifier(node.parent.parent)) {
                                                  ^

TypeError: Cannot read property 'type' of undefined
    at reportIfDoubleFilterLiteral (/Users/nlevingreenhaw/source/app/node_modules/eslint-plugin-lodash/lib/rules/prefer-over-quantifier.js:74:51)
    at /Users/nlevingreenhaw/source/app/node_modules/eslint-plugin-lodash/lib/rules/prefer-over-quantifier.js:86:17
    at EventEmitter.<anonymous> (/Users/nlevingreenhaw/source/app/node_modules/eslint-plugin-lodash/lib/util/lodashUtil.js:85:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/nlevingreenhaw/source/app/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/nlevingreenhaw/source/app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/nlevingreenhaw/source/app/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/nlevingreenhaw/source/app/node_modules/eslint/lib/eslint.js:898:36)
    at Controller.__execute (/Users/nlevingreenhaw/source/app/node_modules/estraverse/estraverse.js:397:31)
```

Probably just need to check that `iteratee` is defined before checking `iteratee.type === 'Identifier'`.

**Comment by ganimomer** [comment]
Thanks for catching this! Fixed in `2.1.4`.
