### ISSUE TITLE
Error: Cannot read property 'getDeclaredVariables' of undefined

### ISSUE THREAD

**Issue by udiudi** [wix/eslint-plugin-lodash#161]
Hi
Getting this error:
```
TypeError: Cannot read property 'getDeclaredVariables' of undefined
    at isOnlyUsedForObject (/path/node_modules/eslint-plugin-lodash/lib/rules/prefer-invoke-map.js:31:51)
    at isFunctionMethodCallOfParam (/path/node_modules/eslint-plugin-lodash/lib/rules/prefer-invoke-map.js:39:114)
```

For this code (based on SourceLocation in func) :
```
return Promise.all([users(), contacts(operationId)])
        .then(collections => _.map(collections, c => c.update(query, update, options)));
```

Any idea what's wrong?

Thanks

**Comment by ganimomer** [comment]
Hi @udiudi,
I tried running the code (without the `return` part, since it doesn't make sense otherwise) and it seems to work fine for me.
Can you tell me what ESLint version you're using?

**Comment by udiudi** [comment]
@ganimomer 
v3.19.0

Thanks
