### ISSUE TITLE
"TypeError: Cannot read property 'prop' of undefined"

### ISSUE THREAD

**Issue by garyking** [wix/eslint-plugin-lodash#194]
If the method isn't a valid Lodash method, then this error is thrown.

Try linting this, for instance: `_.splits(null);`

**Comment by ganimomer** [comment]
Hi @garyking,
Which rule throws this error? Can you give an example of the output?
Thanks

**Comment by garyking** [comment]
I can't determine which rule throws this error, if any specific one at all.

Here's the full output:

```
$ eslint --ignore-path .gitignore .
TypeError: Cannot read property 'prop' of undefined
    at Object.methodSupportsShorthand (/usr/local/lib/node_modules/eslint-plugin-lodash/src/util/methodDataUtil.js:69:113)
    at always (/usr/local/lib/node_modules/eslint-plugin-lodash/src/util/lodashUtil.js:125:32)
    at /usr/local/lib/node_modules/eslint-plugin-lodash/src/util/lodashUtil.js:90:13
    at listeners.(anonymous function).forEach.listener (/usr/local/lib/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
error Command failed with exit code 2.
```
