### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KyleAMathews** [wix/eslint-plugin-lodash#76]
I'm getting this error when running eslint with this plugin.

eslint: 2.9.0
eslint-plugin-lodash: 1.8.4

If I remove this plugin, everything works.

.eslintrc
```javascript
{
  "parser": "babel-eslint",
  "plugins": ["lodash"],
  "extends": ["plugin:lodash/recommend", "eslint-config-airbnb"],
  "rules": {
    "indent": [2, 2, {"SwitchCase": 1}],
    "no-console": [0],
    "func-names": [0],
    "semi": [2, "never"],
    "no-extra-semi": [2],
    "space-before-function-paren": [2, "always"],
    "no-else-return": [0],
    "space-infix-ops": [0],
    "react/prefer-es6-class": [0],
    "react/prefer-stateless-function": [0]
  },
  "globals": {
    "Bugsnag": true,
    "FS": true
  }
}
```

```bash
 ./node_modules/.bin/eslint --debug  --ext .js,.jsx --ignore-path .gitignore .
  eslint:cli Running on files +0ms
  eslint:ignored-paths Using specific ignore file +54ms
  eslint:ignored-paths Adding .gitignore +2ms
  eslint:glob-util Creating list of files to process. +2ms
  eslint:cli-engine Processing /root/RelateRocket/webapp/build/babelRelayPlugin.js +11s
  eslint:cli-engine Linting /root/RelateRocket/webapp/build/babelRelayPlugin.js +1ms
  eslint:config Constructing config for /root/RelateRocket/webapp/build/babelRelayPlugin.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /root/RelateRocket/webapp/.eslintrc +2ms
  eslint:config-file Loading config file: /root/RelateRocket/webapp/.eslintrc +2ms
  eslint:config-file Loading eslint-config-airbnb +108ms
  eslint:config-file Attempting to resolve eslint-config-airbnb +0ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb/index.js +1ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb/rules/react-a11y.js +3ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb/rules/react-a11y.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb/rules/react.js +156ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb/rules/react.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/strict.js +31ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/strict.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/index.js +4ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/index.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/es6.js +1ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/es6.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/legacy.js +157ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/legacy.js +1ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/variables.js +1ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/variables.js +1ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/style.js +21ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/style.js +1ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/node.js +234ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/node.js +1ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/legacy.js +22ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/legacy.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/errors.js +18ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/errors.js +0ms
  eslint:config-file Loading /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/best-practices.js +60ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-config-airbnb-base/rules/best-practices.js +0ms
  eslint:config-file Loading plugin:lodash/recommend +130ms
  eslint:config-file Attempting to resolve eslint-plugin-lodash +0ms
  eslint:config-file Loading JS config file: /root/RelateRocket/webapp/node_modules/eslint-plugin-lodash/lib/index.js +0ms
Cannot convert undefined or null to object
Referenced from: /root/RelateRocket/webapp/.eslintrc
TypeError: Cannot convert undefined or null to object
Referenced from: /root/RelateRocket/webapp/.eslintrc
    at Function.keys (native)
    at Object.deepmerge [as merge] (/root/RelateRocket/webapp/node_modules/eslint/lib/config/config-ops.js:179:20)
    at loadConfigFile (/root/RelateRocket/webapp/node_modules/eslint/lib/config/config-file.js:226:22)
    at load (/root/RelateRocket/webapp/node_modules/eslint/lib/config/config-file.js:494:18)
    at /root/RelateRocket/webapp/node_modules/eslint/lib/config/config-file.js:386:36
    at Array.reduceRight (native)
    at applyExtends (/root/RelateRocket/webapp/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/root/RelateRocket/webapp/node_modules/eslint/lib/config/config-file.js:525:22)
    at loadConfig (/root/RelateRocket/webapp/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/root/RelateRocket/webapp/node_modules/eslint/lib/config.js:126:23)
```

**Comment by ganimomer** [comment]
Looks like the `recommended` config is misspelled. You wrote `recommend` instead, and apparently ESLint took issue with that.

**Comment by ganimomer** [comment]
I opened an issue to ESLint, asking for a clearer error message in this case so this doesn't happen to anyone else.

**Comment by KyleAMathews** [comment]
Ack, thanks 👍 And yeah, the error message you suggested in the Eslint repo issue would have been much more helpful :-)
